import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProviders from "@/context/SessionProvider";
import { ThemeProvider } from "@/context/ThemeProvider";
import { Toaster } from "@/components/ui/sonner"
import ConditionalLayout from "@/components/ConditionalLayout";
import Particles from "@/components/Particles";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SyntheView - Your Personal Interviewer",
  description: "Generated by create next app",
  icons: {
    icon: '/SyntheView_logo.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProviders>
        <ThemeProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-950 text-slate-900 dark:text-white`}
          >
            <Particles />
            <ConditionalLayout>{children}</ConditionalLayout>
            <Toaster/>
          </body>
        </ThemeProvider>
      </SessionProviders>
    </html>
  );
}
